[[libxcrypt]]
arch = "aarch64"
git-tree-sha1 = "adcb9583c38fa25231842e8762d5b9598072fd38"
os = "macos"

    [[libxcrypt.download]]
    sha256 = "a52c0ae7dc6bc448544007c1231147a509c6a2405eed605fbb348604b345f903"
    url = "https://github.com/JuliaBinaryWrappers/libxcrypt_jll.jl/releases/download/libxcrypt-v4.4.38+0/libxcrypt.v4.4.38.aarch64-apple-darwin.tar.gz"
[[libxcrypt]]
arch = "aarch64"
git-tree-sha1 = "b4ceb90e77d72d437c06ff49b046f96754cfb4e0"
libc = "glibc"
os = "linux"

    [[libxcrypt.download]]
    sha256 = "88c42f8f140913d18d35ee0a608ac101d7f15095285f8f6318514db41795ba96"
    url = "https://github.com/JuliaBinaryWrappers/libxcrypt_jll.jl/releases/download/libxcrypt-v4.4.38+0/libxcrypt.v4.4.38.aarch64-linux-gnu.tar.gz"
[[libxcrypt]]
arch = "aarch64"
git-tree-sha1 = "8fa57bcb286239ef73f9318e8838895d880c4ba2"
libc = "musl"
os = "linux"

    [[libxcrypt.download]]
    sha256 = "071ef353f3590ed21ccf8ab2573b08e0baec095c6b006de2f40cf7e00d73228b"
    url = "https://github.com/JuliaBinaryWrappers/libxcrypt_jll.jl/releases/download/libxcrypt-v4.4.38+0/libxcrypt.v4.4.38.aarch64-linux-musl.tar.gz"
[[libxcrypt]]
arch = "aarch64"
git-tree-sha1 = "e12662cac1665865dfdb0bbc39e589b03d224fb7"
os = "freebsd"

    [[libxcrypt.download]]
    sha256 = "32a7f925ccd0782df53a6171cf13a406846c697d0b1f68d49b8a7ffd327d42f3"
    url = "https://github.com/JuliaBinaryWrappers/libxcrypt_jll.jl/releases/download/libxcrypt-v4.4.38+0/libxcrypt.v4.4.38.aarch64-unknown-freebsd.tar.gz"
[[libxcrypt]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "edfaebdd883326ba9792af3929e1481b4b12ab96"
libc = "glibc"
os = "linux"

    [[libxcrypt.download]]
    sha256 = "3767f80f7e3139cf8ece3977f2461dd139a1876b0db4da3288a8a84505475c8e"
    url = "https://github.com/JuliaBinaryWrappers/libxcrypt_jll.jl/releases/download/libxcrypt-v4.4.38+0/libxcrypt.v4.4.38.armv6l-linux-gnueabihf.tar.gz"
[[libxcrypt]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "83c600cc5c7e17383222d2b170e8dd46a56385e9"
libc = "musl"
os = "linux"

    [[libxcrypt.download]]
    sha256 = "f22fd6683e9a384aafed0ba9dfc767ae8ff40c25d917206f2dedbe820fd4fc4d"
    url = "https://github.com/JuliaBinaryWrappers/libxcrypt_jll.jl/releases/download/libxcrypt-v4.4.38+0/libxcrypt.v4.4.38.armv6l-linux-musleabihf.tar.gz"
[[libxcrypt]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "86dbc130d856c05f759ecfa1db22850d61e89494"
libc = "glibc"
os = "linux"

    [[libxcrypt.download]]
    sha256 = "531b0914cb073bbdc24c800445481284bfbfc284bc4e12855cbf26cdeae92f45"
    url = "https://github.com/JuliaBinaryWrappers/libxcrypt_jll.jl/releases/download/libxcrypt-v4.4.38+0/libxcrypt.v4.4.38.armv7l-linux-gnueabihf.tar.gz"
[[libxcrypt]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "5bdd022d49f83d07f2a203475fb83845976867d8"
libc = "musl"
os = "linux"

    [[libxcrypt.download]]
    sha256 = "f34711b99513dea7a1c8bffae93a5e40b0e57ed895f66ac97db119ae0cb36464"
    url = "https://github.com/JuliaBinaryWrappers/libxcrypt_jll.jl/releases/download/libxcrypt-v4.4.38+0/libxcrypt.v4.4.38.armv7l-linux-musleabihf.tar.gz"
[[libxcrypt]]
arch = "i686"
git-tree-sha1 = "c553490bc517d0017cdfa3983e9a5a16615dc0f2"
libc = "glibc"
os = "linux"

    [[libxcrypt.download]]
    sha256 = "0dc709b1143716a38923fb630c36be3734194ed83e1fb6573207175a30de71f7"
    url = "https://github.com/JuliaBinaryWrappers/libxcrypt_jll.jl/releases/download/libxcrypt-v4.4.38+0/libxcrypt.v4.4.38.i686-linux-gnu.tar.gz"
[[libxcrypt]]
arch = "i686"
git-tree-sha1 = "14ef231a70f123217377fb04289d4fe03dda0058"
libc = "musl"
os = "linux"

    [[libxcrypt.download]]
    sha256 = "5ebbb996447a2f078eba7ee36c6c6ff7880ff8891a6649428c73df1124372065"
    url = "https://github.com/JuliaBinaryWrappers/libxcrypt_jll.jl/releases/download/libxcrypt-v4.4.38+0/libxcrypt.v4.4.38.i686-linux-musl.tar.gz"
[[libxcrypt]]
arch = "powerpc64le"
git-tree-sha1 = "46bd9d0565026068a277a471706eca2973c2dc7e"
libc = "glibc"
os = "linux"

    [[libxcrypt.download]]
    sha256 = "3f6cea11666d7a9aa6928dc860398dd106e93e03bb3bad741367eb30135811e3"
    url = "https://github.com/JuliaBinaryWrappers/libxcrypt_jll.jl/releases/download/libxcrypt-v4.4.38+0/libxcrypt.v4.4.38.powerpc64le-linux-gnu.tar.gz"
[[libxcrypt]]
arch = "riscv64"
git-tree-sha1 = "b2e8360fb16f32aa12096feb8dade2d3725534c0"
libc = "glibc"
os = "linux"

    [[libxcrypt.download]]
    sha256 = "e43b530eda7c1eeef25572adaf420a710a8736b51306ebae59308190a85cdca1"
    url = "https://github.com/JuliaBinaryWrappers/libxcrypt_jll.jl/releases/download/libxcrypt-v4.4.38+0/libxcrypt.v4.4.38.riscv64-linux-gnu.tar.gz"
[[libxcrypt]]
arch = "x86_64"
git-tree-sha1 = "d66f09ea456114b81c37154e69c2632a293ff6d9"
os = "macos"

    [[libxcrypt.download]]
    sha256 = "cc1bc7aad31157511bc8ec2598971fd7e37bc0747e8e0f98a8bfc3727d1d6106"
    url = "https://github.com/JuliaBinaryWrappers/libxcrypt_jll.jl/releases/download/libxcrypt-v4.4.38+0/libxcrypt.v4.4.38.x86_64-apple-darwin.tar.gz"
[[libxcrypt]]
arch = "x86_64"
git-tree-sha1 = "be2e31db8c4f6a75784957956eace285f22095b5"
libc = "glibc"
os = "linux"

    [[libxcrypt.download]]
    sha256 = "9cad694c0dcad0686f76cf535aae8e44ebfff05f5d736086f59436932e4abf7a"
    url = "https://github.com/JuliaBinaryWrappers/libxcrypt_jll.jl/releases/download/libxcrypt-v4.4.38+0/libxcrypt.v4.4.38.x86_64-linux-gnu.tar.gz"
[[libxcrypt]]
arch = "x86_64"
git-tree-sha1 = "1162f4d8c981ce62d2f7a17d8a0938c80c4a2b50"
libc = "musl"
os = "linux"

    [[libxcrypt.download]]
    sha256 = "a8b365de3f17059cecf11751d3cf6d58b139539741c23469afd71eab5f30c5de"
    url = "https://github.com/JuliaBinaryWrappers/libxcrypt_jll.jl/releases/download/libxcrypt-v4.4.38+0/libxcrypt.v4.4.38.x86_64-linux-musl.tar.gz"
[[libxcrypt]]
arch = "x86_64"
git-tree-sha1 = "6b70146d7deab1fa665fd653877bb71c3db520b8"
os = "freebsd"

    [[libxcrypt.download]]
    sha256 = "051958945b7ddb51e23d785fc6a3284a32c960d606c5a8c12018199e934cff71"
    url = "https://github.com/JuliaBinaryWrappers/libxcrypt_jll.jl/releases/download/libxcrypt-v4.4.38+0/libxcrypt.v4.4.38.x86_64-unknown-freebsd.tar.gz"
