# Autogenerated wrapper script for libxcrypt_jll for x86_64-apple-darwin
export libcrypt

JLLWrappers.@generate_wrapper_header("libxcrypt")
JLLWrappers.@declare_library_product(libcrypt, "@rpath/libcrypt.2.dylib")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libcrypt,
        "lib/libcrypt.2.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
